name: 'Ai Pull Request Explainer'
description: 'Automatically generates PR descriptions by analyzing code diffs using LLMs like Gemini.'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for Octokit'
    required: true
    default: ${{ github.token }} # مقدار پیش‌فرض کلیدی
  GEMINI_API_KEY:
    description: 'Gemini API Key'
    required: true

runs:
  using: 'node20'
  main: 'dist/main.mjs'
  