name: 'Ai Pull Request Explainer'
description: >
  Gemini AI GitHub Action for PR diffs: crafts structured descriptions, titles, & applies labels. Streamlines reviews.

branding:
  icon: 'book-open'
  color: 'green'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for Octokit'
    required: true
    default: ${{ github.token }}
  GEMINI_API_KEY:
    description: 'Gemini API Key'
    required: true

runs:
  using: 'node20'
  main: 'dist/main.mjs'
