name: 'Ai Pull Request Explainer'
description: >
  This GitHub Action employs Large Language Models (like Gemini) to analyze pull request diffs. 
  It automatically generates detailed, structured technical descriptions, Conventional Commit titles, 
  and suggests appropriate GitHub labels. These labels can also be automatically applied, 
  streamlining the code review and documentation workflow.

branding:
  icon: 'book-open'
  color: 'green'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for Octokit'
    required: true
    default: ${{ github.token }}
  GEMINI_API_KEY:
    description: 'Gemini API Key'
    required: true

runs:
  using: 'node20'
  main: 'dist/main.mjs'
