on:
  pull_request:
    types: [synchronize, reopened, labeled]

jobs:
  explainer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display action.yml content # مرحله دیباگ جدید
        run: |
          echo "--- Content of action.yml at runtime ---"
          cat ./action.yml
          echo "---------------------------------------"
        shell: bash

      - name: PR Auto Describe
        uses: ./
        with:
          # GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}