on:
  pull_request:
    types: [synchronize, reopened, labeled]

jobs:
  explainer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Tokens and Secrets at Workflow Level # <--- مرحله جدید
        run: |
          echo "Workflow GITHUB_TOKEN context: ${{ github.token && 'Token is available' || 'Token is NOT available' }}"
          echo "Workflow GEMINI_API_KEY secret: ${{ secrets.GEMINI_API_KEY && 'Secret is available' || 'Secret is NOT available' }}"
        shell: bash

      - name: Display action.yml content # مرحله دیباگ جدید
        run: |
          echo "--- Content of action.yml at runtime ---"
          cat ./action.yml
          echo "---------------------------------------"
        shell: bash

      - name: PR Auto Describe
        uses: ./
        with:
          # GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}